# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OggFpBPiWGKzT4f0L4MrZ035gfNjXX9k
"""



import pandas as pd

# Load the dataset
file_path = '/content/dw.csv'
df = pd.read_csv(file_path)

# Display basic info and first few rows
print("Data Overview:")
display(df.info())
display(df.head())

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Basic Cleaning: Fill or drop missing values (example: filling with 'Unknown' for strings)
# df = df.fillna('Unknown')

# 3. Example Transformation: Strip whitespace from string columns
str_cols = df.select_dtypes(include=['object']).columns
df[str_cols] = df[str_cols].apply(lambda x: x.str.strip() if hasattr(x, 'str') else x)

print("Transformations complete. Updated DataFrame shape:", df.shape)
display(df.head())

# Convert Zscore to numeric, setting errors='coerce' to turn invalid parsing into NaN
df['Zscore'] = pd.to_numeric(df['Zscore'], errors='coerce')

# Check for nulls after conversion
null_count = df['Zscore'].isnull().sum()
print(f"Conversion complete. Number of non-numeric Zscore values (now NaN): {null_count}")

# Display the statistics for the Zscore column
display(df['Zscore'].describe())

"""### Advanced Data Transformation
In this step, we will:
1. Clean the `district_rank` and `island_rank` columns by removing text like '(NEW)'.
2. Replace the hyphen '-' in the `stream` column with 'UNKNOWN'.
"""